Really improve react's Component
iw1-hdka/mini-react pull request #6
Opened 2019-02-10 10:38 UTC by vodkhard

2019-02-10 20:16 UTC, kconde2 requested changes
Très bien comme component modèle. Faudrait qu'on le valide, vite pour que je puisse le **tester rapidement**  avec le routing en faisant un rebase de develop sur ma branche A part la fin de ligne à ajouter.
Je ne vois pas l'usage de `process_access` et `string_interpolate`?

2019-02-10 20:16 UTC, kconde2 commented on js/miniDOM.js
> +}
ajouter une fin de ligne, ici

2019-02-10 21:24 UTC, dachic commented on js/miniDOM.js
> +        ...domEl.props
Des explications sur "...domEl.props" ?

2019-02-10 21:24 UTC, dachic commented on js/utils.js
> +        && /^class\s/.test(Function.prototype.toString.call(func));
Tu peux expliquer cette ligne stp ?

2019-02-10 21:24 UTC, dachic commented on js/miniDOM.js
> +        vDOM.forEach(child => root.appendChild(document.createTextNode(child)))
Pourquoi quand vDOM est un tableau tu considères "child" comme du texte ?

2019-02-13 17:37 UTC, vodkhard commented on js/miniDOM.js
> +        vDOM.forEach(child => root.appendChild(document.createTextNode(child)))
C’est dû à un petit soucis dans mon algo pour l’instant. Quand je passe un children à un composant qui l’affiche en tant que children je me retrouve avec un tableau à la fin et pas un string donc c’est un petit fix temporaire

2019-02-13 17:38 UTC, vodkhard commented on js/miniDOM.js
> +        ...domEl.props
J’applatis domEl.props après avoir définis une key pour avoir une key par défaut

2019-02-13 17:39 UTC, vodkhard commented on js/utils.js
> +        && /^class\s/.test(Function.prototype.toString.call(func));
C’est juste une regex qui regarde si j’ai declaré mon Component en tant que class ou en ttant que fonction

2019-02-16 08:57 UTC, merged